### ISSUE TITLE
Parser fails with gRPC timeout exceeded when feeding big CSV files

### ISSUE THREAD

**Issue by tb0hdan** [viktorminko/microservice-task#8]

**Comment by viktorminko** [comment]
Put wg.Wait() in wrong place, so request weren't really concurrent. Fixed in https://github.com/viktorminko/microservice-task/commit/aad20a232a34a955e107e703584022c8f8be1768 

Should be better now

**Comment by viktorminko** [comment]
I've limited amount of concurrent DB connections, this should help to avoid DB connection errors. https://github.com/viktorminko/microservice-task/commit/dc385c68de8a67da687e7fcc8276b089493c9617
